name: Publish

on:
  push:

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-22.04"

    environment:
      name: deploy

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: "Install dependencies"
        run: "scripts/install"
      - name: "Build package & docs"
        run: "scripts/build"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      - name: "Upload artifacts"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: starlette
          path: "dist/*"
